services:
  - type: web
    name: browser-use-webui
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"